export { simpleAlert } from './dialogs/simple-alert'
export { simpleConfirm } from './dialogs/simple-confirm'
export { simpleModal } from './dialogs/simple-modal'
export { simplePrompt } from './dialogs/simple-prompt'
export { SimpleDialogContainer } from './simple-dialog-container'
